**Name: Chrysille Grace L. So**

**Course: BS CS-ST**

**ID Num: 122**

# Zomato Exercise

Zomato is a restaurant aggregator website. The platform provides information, menus and user-reviews of restaurants as well as food delivery options from partner restaurants in select cities. You have been provided 3 datasets:

- zomato.csv contains restaurant information like average_cost_for_two, cuisines
- location.csv contains location of the restaurants like address, city, locality & etc
- ratings.csv contains aggregate rating for each restaurant

The different files are connected using the `id` columns which can be found in the different files. The id column is a unique identifier to represent a restaurant. You can use this to **merge** the different files.

In [16]:
import pandas as pd
import numpy as np

In [48]:
#Additional: To avoid re-uploading csv, load directly from github
#zomato.csv
zomato_url = 'https://raw.githubusercontent.com/silleeSo/DATA100_graded3/refs/heads/main/zomato.csv'
zomato_df = pd.read_csv(zomato_url)

#location.csv
location_url = 'https://raw.githubusercontent.com/silleeSo/DATA100_graded3/refs/heads/main/location.csv'
location_df = pd.read_csv(location_url)

#ratings.csv
ratings_url = 'https://raw.githubusercontent.com/silleeSo/DATA100_graded3/refs/heads/main/ratings.csv'
ratings_df = pd.read_csv(ratings_url)

Print to confirm successful import:

In [18]:
zomato_df.head()

,id,average_cost_for_two,book_url,cuisines,currency,deeplink,events_url,featured_image,has_online_delivery,has_table_booking,...,is_delivering_now,is_table_reservation_supported,is_zomato_book_res,menu_url,mezzo_provider,name,photos_url,price_range,thumb,url
0,6316125,1000,NaN,"Japanese, Ramen",P,zomato://restaurant/6316125,https://www.zomato.com/manila/mendokoro-ramenb...,https://b.zmtcdn.com/data/reviews_photos/971/2...,0,0,...,0,0,0.0,https://www.zomato.com/manila/mendokoro-ramenb...,OTHER,Mendokoro Ramenba,https://www.zomato.com/manila/mendokoro-ramenb...,3,https://b.zmtcdn.com/data/reviews_photos/971/2...,https://www.zomato.com/manila/mendokoro-ramenb...
1,18409457,1300,NaN,"Korean, Grill, Korean BBQ",P,zomato://restaurant/18409457,https://www.zomato.com/manila/soban-k-town-gri...,https://b.zmtcdn.com/data/res_imagery/18290970...,0,0,...,0,0,0.0,https://www.zomato.com/manila/soban-k-town-gri...,OTHER,Soban K-Town Grill,https://www.zomato.com/manila/soban-k-town-gri...,3,https://b.zmtcdn.com/data/res_imagery/18290970...,https://www.zomato.com/manila/soban-k-town-gri...
2,6307689,1600,NaN,"American, Filipino",P,zomato://restaurant/6307689,https://www.zomato.com/manila/filling-station-...,https://b.zmtcdn.com/data/pictures/9/6307689/b...,0,0,...,0,0,0.0,https://www.zomato.com/manila/filling-station-...,OTHER,Filling Station,https://www.zomato.com/manila/filling-station-...,4,https://b.zmtcdn.com/data/pictures/9/6307689/b...,https://www.zomato.com/manila/filling-station-...
3,18581637,1000,NaN,Korean,P,zomato://restaurant/18581637,https://www.zomato.com/manila/romantic-baboy-t...,https://b.zmtcdn.com/data/reviews_photos/cc1/a...,0,0,...,0,0,0.0,https://www.zomato.com/manila/romantic-baboy-t...,OTHER,Romantic Baboy,https://www.zomato.com/manila/romantic-baboy-t...,3,https://b.zmtcdn.com/data/reviews_photos/cc1/a...,https://www.zomato.com/manila/romantic-baboy-t...
4,6315438,3000,NaN,"Seafood, American, Mediterranean, Japanese",P,zomato://restaurant/6315438,https://www.zomato.com/manila/niu-by-vikings-b...,https://b.zmtcdn.com/data/pictures/chains/8/63...,0,0,...,0,0,0.0,https://www.zomato.com/manila/niu-by-vikings-b...,OTHER,NIU by Vikings,https://www.zomato.com/manila/niu-by-vikings-b...,4,https://b.zmtcdn.com/data/pictures/chains/8/63...,https://www.zomato.com/manila/niu-by-vikings-b...

In [19]:
location_df.head()

,id,address,city,city_id,country_id,latitude,locality,locality_verbose,longitude,zipcode
0,6316125,"V. Corporate Center, Soliman Street, Salcedo V...",Makati City,63,162,14.560313,Salcedo Village,"Salcedo Village, Makati City",121.024638,NaN
1,18409457,"Level 3, Greenbelt 3, Ayala Center, Greenbelt,...",Makati City,63,162,14.552137,"Greenbelt 3, San Lorenzo, Makati City","Greenbelt 3, San Lorenzo, Makati City, Makati ...",121.021325,NaN
2,6307689,"5012 P. Burgos Street, Poblacion, Makati City ...",Makati City,63,162,14.563144,Poblacion,"Poblacion, Makati City",121.029800,1210.0
3,18581637,"CKB Centre, Tomas Morato Avenue Corner Scout R...",Quezon City,63,162,14.633713,Tomas Morato,"Tomas Morato, Quezon City",121.035026,NaN
4,6315438,"Sixth Floor, SM Aura Premier, C5 Road Corner 2...",Taguig City,63,162,14.546236,"SM Aura Premier, Bonifacio Global City, Taguig...","SM Aura Premier, Bonifacio Global City, Taguig...",121.054365,NaN

In [20]:
ratings_df.head()

         id  aggregate_rating rating_color rating_text  votes
0   6316125               4.9       3F7E00   Excellent   1394
1  18409457               4.6       3F7E00   Excellent    602
2   6307689               4.0       5BA829   Very Good    563
3  18581637               4.0       5BA829   Very Good    413
4   6315438               4.6       3F7E00   Excellent    960

1. Merge the zomato, location & ratings file into a signle dataframe and store it to the `merged_df` variable **(3pts)**

In [21]:
merged_df = pd.merge(zomato_df, location_df, on='id')
merged_df = pd.merge(merged_df, ratings_df, on='id')

print(merged_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6830 entries, 0 to 6829
Data columns (total 35 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              6830 non-null   int64
 1   average_cost_for_two            6830 non-null   int64
 2   book_url                        518 non-null    object
 3   cuisines                        6829 non-null   object
 4   currency                        6830 non-null   object
 5   deeplink                        6830 non-null   object
 6   events_url                      6830 non-null   object
 7   featured_image                  6248 non-null   object
 8   has_online_delivery             6830 non-null   int64
 9   has_table_booking               6830 non-null   int64
 10  include_bogo_offers             6830 non-null   bool
 11  is_book_form_web_view           6828 non-null   float64
 12  is_delivering_now               6830 non-null   int64
 13  is_table_reservation_supported  6830 non-null   int64
 14  is_zomato_book_res              6828 non-null   float64
 15  menu_url                        6830 non-null   object
 16  mezzo_provider                  6828 non-null   object
 17  name                            6830 non-null   object
 18  photos_url                      6830 non-null   object
 19  price_range                     6830 non-null   int64
 20  thumb                           6248 non-null   object
 21  url                             6830 non-null   object
 22  address                         6830 non-null   object
 23  city                            6830 non-null   object
 24  city_id                         6830 non-null   int64
 25  country_id                      6830 non-null   int64
 26  latitude                        6830 non-null   float64
 27  locality                        6830 non-null   object
 28  locality_verbose                6830 non-null   object
 29  longitude                       6830 non-null   float64
 30  zipcode                         117 non-null    float64
 31  aggregate_rating                6830 non-null   float64
 32  rating_color                    6830 non-null   object
 33  rating_text                     6830 non-null   object
 34  votes                           6830 non-null   int64
dtypes: bool(1), float64(6), int64(10), object(18)
memory usage: 1.8+ MB
None

In [22]:
assert (6830, 35)==merged_df.shape

cols = ['id', 'address', 'city', 'city_id', 'country_id', 'latitude',
       'locality', 'locality_verbose', 'longitude', 'zipcode',
       'aggregate_rating', 'rating_color', 'rating_text', 'votes',
       'average_cost_for_two', 'book_url', 'cuisines', 'currency', 'deeplink',
       'events_url', 'featured_image', 'has_online_delivery',
       'has_table_booking', 'include_bogo_offers', 'is_book_form_web_view',
       'is_delivering_now', 'is_table_reservation_supported',
       'is_zomato_book_res', 'menu_url', 'mezzo_provider', 'name',
       'photos_url', 'price_range', 'thumb', 'url']

assert sorted(merged_df.columns) == sorted(cols)

2. Create a function that returns the average aggregate rating for each city. Expected returned value is a Series datatype which contains name of city as index and average aggregate rating as value. **(2pts)**

In [23]:
def exercise_2(merged_df):
    avg_ratings = merged_df.groupby('city')['aggregate_rating'].mean()
    return avg_ratings

In [24]:
res_series = exercise_2(merged_df)
assert True == np.isclose(3.302075, res_series[res_series.index == 'Pasay City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]
assert True == np.isclose(1.890741, res_series[res_series.index == 'Valenzuela City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]
assert True == np.isclose(1.558333, res_series[res_series.index == 'Malabon City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]

3. Using the apply function of pandas convert the rating_text to a numeric equivalent. You are to introduce a new column in merged_df called `rating_numeric` which is based on the value from rating_text: **(3pts)**

Excellent = 5 <br>
Very Good = 4 <br>
Good = 3 <br>
Average = 2 <br>
Poor = 1 <br>
Not rated = 0 <br>

In [25]:
numerical_rating = {
    'Excellent': 5,
    'Very Good': 4,
    'Good': 3,
    'Average': 2,
    'Poor': 1,
    'Not rated': 0
}

# get() is used to fetch value from map, value defaults to 0 if not found
merged_df['rating_numeric'] = merged_df['rating_text'].apply(lambda x: numerical_rating.get(x, 0))

# Print ratings columns to confirm
print(merged_df[['rating_text', 'rating_numeric']].head())

  rating_text  rating_numeric
0   Excellent               5
1   Excellent               5
2   Very Good               4
3   Very Good               4
4   Excellent               5

In [26]:
assert 868 == merged_df[merged_df.rating_numeric == 0].shape[0]
assert True == ('rating_numeric' in merged_df.columns)

4. Create a function which filters the merged dataframe to only contain rows coming in from a specific city. Expected returned value is a dataframe **(2pts)**

In [32]:
def exercise_4(merged_df, city):
    filtered_df = merged_df[merged_df['city'] == city]
    return filtered_df

In [33]:

assert 'Makati City' == exercise_4(merged_df, 'Makati City').city.unique()[0]
assert (976, 36) == exercise_4(merged_df, 'Makati City').shape

assert 'Mandaluyong City' == exercise_4(merged_df, 'Mandaluyong City').city.unique()[0]
assert (443, 36) == exercise_4(merged_df, 'Mandaluyong City').shape

assert (0, 36) == exercise_4(merged_df, 'Quezon  City').shape

5. Create a function to filter the dataframe to only contain certain columns passed in the function. Expected returned value is a dataframe **(1pt)**

In [36]:
def exercise_5(merged_df, cols_to_filter):
    available_columns = [col for col in cols_to_filter if col in merged_df.columns]
    filtered_df = merged_df[available_columns]
    return filtered_df

In [37]:
cols = ['name', 'cuisines', 'city', 'aggregate_rating']
assert sorted(cols) == sorted(exercise_5(merged_df, cols).columns)
assert (6830, 4) == exercise_5(merged_df, cols).shape

cols = ['average_cost_for_two', 'book_url', 'cuisines', 'currency', 'deeplink',
       'events_url', 'featured_image', 'has_online_delivery',
       'has_table_booking', 'include_bogo_offers', 'is_book_form_web_view']
assert sorted(cols) == sorted(exercise_5(merged_df, cols).columns)
assert (6830, 11) == exercise_5(merged_df, cols).shape

6.  What is the most common restaurant name in the dataset? **(2pts)** Write down your answer and show code used to come up with the answer.

In [40]:
common_name = merged_df['name'].value_counts().idxmax()
common_count = merged_df['name'].value_counts().max()

print(f"The most common restaurant name: {common_name}")
print(f"The number of occurences: {common_count}")

The most common restaurant name: Starbucks
The number of occurences: 99

7. Which restaurant has the most expensive average cost for two? **(2pts)** Write down your answer and show code used to come up with the answer.

In [41]:
most_expensive = merged_df.loc[merged_df['average_cost_for_two'].idxmax()] #get row index

print(f"Most Expensive Restaurant: {most_expensive['name']}")
print(f"Average Cost for Two: {most_expensive['average_cost_for_two']}")

Most Expensive Restaurant: The Tasting Room
Average Cost for Two: 10000

8. How many restaurants do not have a zipcode? **(1pt)** Write down your answer and show code used to come up with the answer.

In [42]:
no_zipcode_count = merged_df['zipcode'].isna().sum()

print(f"Number of restaurants without a zipcode: {no_zipcode_count}")

Number of restaurants without a zipcode: 6713

9. How many restaurants in the dataset allow online delivery? **(1pt)** Write down your answer and show code used to come up with the answer.

In [43]:
online_delivery_count = merged_df[merged_df['has_online_delivery'] == 1].shape[0]

print(f"Number of restaurants that allow online delivery: {online_delivery_count}")

Number of restaurants that allow online delivery: 0

10. Which locatlity has more expensive food? Poblacion or Salcedo Village? **(3pts)** Write down your answer and show code used to come up with the answer.

In [45]:
ave_cost_poblacion = merged_df[merged_df['locality'] == 'Poblacion']['average_cost_for_two'].mean()
ave_cost_salcedo = merged_df[merged_df['locality'] == 'Salcedo Village']['average_cost_for_two'].mean()

if ave_cost_poblacion > ave_cost_salcedo:
    expensive_locality = 'Poblacion'
    expensive_cost = ave_cost_poblacion
else:
    expensive_locality = 'Salcedo Village'
    expensive_cost = ave_cost_salcedo

print(f"locality with more expensive food: {expensive_locality}")
print(f"average cost: {expensive_cost:.2f}.")

locality with more expensive food: Salcedo Village
average cost: 989.10.